# -*- coding: utf-8 -*-
"""Python for Chemists Examples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQgDuuw_RO46hsjFJvuGxPzO17X3oWAm

Example 1
"""

# How Many molecules of water are there in a 250 mL glass of water?
# Take Density of rho(H2O(l)) = 1 g cm-3 and the molar mass, M(H2O)=18 g mol-1.



#Solution

#Avagadro Constant, in mol-1
N_A = 6.022e23

V = int(input('the Volume of water is: '))
Molar_Mass = 18     # molar mass in g.mol-1.
rho = 1    # density in g.cm-3.

# Mass of Water(H2O), in g.
m = rho*V   # Mass of Water(H2O) is m.

print(m)

# Amount of water(n), in mol.
n = m/Molar_Mass

print(n) # n values in mol.

#the Number of water molecules is then N=nN_A.
N = n*N_A

print(N)

"""Example 2"""

# The speed of sound in a gas of molar mass (M) at temperature (T) is c = sqrt(gamma*R*T/M), where R is the gas constant and
#for air the adiabatic index, gamma = 7/5. Estimate the speed of sound in air at
# a) 25 degC, b) -20 degC, take M = 29 gmol-1.


#Solution.

import numpy as np
# The gas constant in J.K-1.mol-1.
R = 8.314

# Mean molar mass of air , in kg.mol-1
M = 29/1000
# The ratio of heat capacities C_p / C_v (adiabatic index) for a diatomic gas
gamma = 7/5  # Set gamma directly as per problem description (7/5 = 1.4)

# Assuming f as a factor to calculate velocity of air at different temperature, in m.s-1.K-1/2.
# c = f(sqrt(T)), f = sqrt(gamma*R/M),
# c = sqrt(gamma*R*T/M)
f = np.sqrt(gamma*R/M)
print(f)

# Convert the first temperature from degC to K. a) 25 degC. b) -20 degC
T = float(input('Enter the temperature in degC: '))
T1 = T + 273.1
f*np.sqrt(T1)

"""Example 3"""

# Acetic acid (CH3COOH) is a weak acid with pKa = 4.756. What is the pH of a 0.1M solution of acetic acid water?

 # Solution

 # The pKa of acetic acid, log10 of the acid dissociation  constant.
pKa = 4.756         # by definition pKa = -log(Ka).
Ka = 10**-4.756
Ka

import numpy as np
# 'Standard' amount concentration, 1M = 1 mol.dm-3.
c_std = 1
#the concentration of acid.
c = float(input('The concentration of acid is: '))

# The concentration of hydrogen ions at equilibrium(M).
x = np.sqrt(Ka*c*c_std)
x

pH = -np.log10(x)
pH

"""Example 4"""

import numpy as np
# the gas constant in J.K-1.mol-1.
R = 8.314
# The standard molar enthalpy of formation of NH3(g) in kJ.mol-1.
DfH_NH3 = float(input('The standard molar enthalpy of formation of NH3(g) is: '))

# Standard molar entropies for H2(g), N2(g) and NH3(g) in J.K-1.mol-1.
Sm_H2 = float(input('The standard molar entropy of H2(g) is: '))
Sm_N2 = float(input('The standard molar entropy of N2(g) is: '))
Sm_NH3 = float(input('The standard molar entropy of NH3(g) is: '))

# The temperature considered for the equilibrium.
T = float(input('The temperature considered for the equilibrium is: '))

# The standard entropies and enthalpies of reaction is.
# If the elements present in either reactants side or products side thier enthalpy of formation can be Zero.
DrH_H2 = 0
DrH_N2 = 0
DrH = 2*DfH_NH3      # Standard enthalpy of reaction in kJ.mol-1.

# Standard entropy of reaction in J.K-1.mol-1
DrS = 2*Sm_NH3 - 3*Sm_H2 - Sm_N2
DrS
DrH,DrS

DrG = DrH - T*DrS/1000      # If DrG values are negitive the raection forward to form products.
DrG

# DrG standard is equal to -RTlnK. by this if K>>>1 favours products.
K = np.exp(-DrG*1000/(R*T))
K

"""**Chapter** **2**  Exercise P2.1"""

# Arrhenius equation of Temperature dependence of the reaction rate coefficient is,
# k = Aexp(-Ea/RT)
# lnk = lnA - Ea/RT.
# A is exponential constant, changing to different temperature (T1,T2).
# reaction rate k changes to k1 and k2.

import numpy as np
# The gas constant in J.K-1.mol-1.
R = 8.314
T1 = float(input('The initial temperature considered for the equilibrium is: '))
T2 = float(input('The final temperature considered for the equilibrium is: '))
T1 , T2 = T1 + 273.15 , T2 + 273.1

# Calculate the activation energy, in J.mol-1.
Ea = R*np.log(10)/(1/T1 - 1/T2)
Ea

"""Execise P2.2"""

# The number of moles of C55H104O6 (fat).
M_H, M_C, M_O = 1, 12, 16
# molar mass of average fat molecule in g.mol-1.
M_fat = 55*M_C + 104*M_H + 6*M_O
# The number of moles of fat molecules in given wieght
n_fat = 1000/M_fat
n_fat

# Complete rreaction is,
# C55H104O6 + 78O2 ---->  52H2O + 55CO2
n_C55H104O6 = n_fat
n_78O2 = 78*n_fat
n_52H2O = 52*n_fat
n_55CO2 = 55*n_fat
print(f'{n_C55H104O6} moles of C55H104O6')
print(f'{n_78O2} moles of 78O2')
print(f'{n_52H2O} moles of 52H2O')
print(f'{n_55CO2} moles of 55CO2')

# The Corresponding mass of CO2 and H2O.
M_CO2, M_H2O = 44, 18
m_55CO2 = n_55CO2*M_CO2
m_52H2O = n_52H2O*M_H2O
print(f'The mass of CO2 is: {m_55CO2:.0f} g')
print(f'The mass of H2O is: {m_52H2O:.0f} g')

perc_CO2 = (55*M_C + 2/3*6*M_O)/ M_fat*100
perc_H2O = (104*M_H + 1/3*6*M_O)/ M_fat*100
print(f'The percentage of CO2 is: {perc_CO2} %')
print(f'The percentage of H2O is: {perc_H2O} %')

perc_CO2_rounded = round(perc_CO2, 2)
perc_H2O_rounded = round(perc_H2O, 2)

print(f'Rounded percentage of CO2: {perc_CO2_rounded} %')
print(f'Rounded percentage of H2O: {perc_H2O_rounded} %')

# Alternatively, you can format directly in the f-string
print(f'Formatted percentage of CO2: {perc_CO2:.2f} %')
print(f'Formatted percentage of H2O: {perc_H2O:.2f} %')

"""Exercise P2.3"""

import numpy as np
# The gas constant in J.K-1.mol-1.
R = 8.314
# Molar enthalpy of vaporiszation of water, kJ.mol-1.
DvapH = float(input('The molar enthalpy of vaporiszation of water is: '))
# Normal boiling poiint of water at sea level, k.
T0 = 100 + 275


# Atmospheric scale height, H , in m.
H = float(input('The Atmospheric scale height is: '))

# Height of Everest, m.
z = 8849
# Atmospheric pressure at sea level, atm.
p0 = 1

# Atmospheric pressure at the summit of everest, atm.
p1 = p0*np.exp(-z/H)
p1

# The air pressure at the summit, by integrating the claisius-clapeyron equation yields,
# ln(p1/p0)= -DvapH/R(1/T0-1/T1)
# by rearranging above euation, T1 = 1/(1/To-R/DvapH*ln(p1/p0))
# NB convert DvapH from Kj.mol-1 to K.mol-1.
T1 = 1/(1/T0 - R/1000/DvapH*np.log(p1/p0))
T1

"""**Chapter-3** **Examples**

"""

# The Mass of linear alkane, CnH2n+2.
# Molar masses of carbon, hydrogen atoms (g.mol-1).
mC, mH = 12.0107, 1.00784
# String formating template.
fmt = 'Mass of {:5s}: {:6.3f} g.mol-1'

# Loop through a few different values for 'n' (number of carbon atoms)
for n in range(1,10): # For n from 1 to 8 (C1H4 to C8H18)
  nH = 2*n + 2
  formula = 'C{}H{}'.format(n, nH)      # or f'C{n}H{nH}'
  print(fmt.format(formula, mC*n + mH*nH))

"""E3.2"""

h, h_units = 6.62607015e-33, 'J.s'
c, c_units = 299792458, 'm.s-1'
kB, kB_units = 1.380649e-23, 'J.K-1'
R, R_units = 8.314462618, 'J.K.mol-1'
N_A, N_A_units = 6.02214076e+23, 'mol-1'
# make single string
s = (f'h = {h:8.3e} {h_units}\n'
     f'c = {c:5.3e} {c_units}\n'
     f'kB = {kB:4.3e} {kB_units}\n'
     f'R = {R:4.3f} {R_units}\n'
     f'N_A = {N_A:8.3e} {N_A_units}')
print(s)

"""**Exercise 3.6**"""

# Triple point of CO2 (K, Pa).
T3_CO2, p3_CO2 = 216.58, 5.185e5
# Enthalpy of fusion of CO2 (kJ.mol-1).
DfusH_CO2 = float(input('The Enthalpy of fusion of CO2 is: '))
# Entropy of fusion of CO2 (J.K-1.mol-1).
DfusS_CO2 = float(input('The Entropy of fusion of CO2 is: '))
# Enthalpy of vaporization of CO2 (kJ.mol-1).
DvapH_CO2 = float(input('The Enthalpy of vaporization of CO2 is: '))
# Entropy of vaporization of CO2 (J.K-1.mol-1).
DvapS_CO2 = float(input('The Entropy of vaporization of CO2 is: '))

# Triple point of H2O (K,Pa).
T3_H2O, p3_H2O = 273.16, 611.73
# # Enthalpy of fusion of H2O (kJ.mol-1).
DfusH_H2O = float(input('The Enthalpy of fusion of H2O is: '))
# Entropy of fusion of H2O (J.K-1.mol-1).
DfusS_H2O = float(input('The Entropy of fusion of H2O is: '))
# Enthalpy of vaporization of H2O (kJ.mol-1).
DvapH_H2O = float(input('The Enthalpy of vaporization of H2O is: '))
# Entropy of vaporization of H2O (J.K-1.mol-1).
DvapS_H2O = float(input('The Entropy of vaporization of H2O is: '))

print('Name' + ' '*2 + 'Units' + ' '*12 + 'CO2' + ' '*8 + 'H2O')
print('--'*20)
print('p3     /Pa          ', f'{p3_CO2:8.0f}  {p3_H2O:8.3f}')
print('T3     /K           ', f'{T3_CO2:8.3f}  {T3_H2O:8.3f}')
print('DfusH  /kJ.mol-1   ', f'{DfusH_CO2:8.3f}  {DfusH_H2O:8.3f}')
print('DfusS  /J.K-1.mol-1', f'{DfusS_CO2:8.3f}  {DfusS_H2O:8.3f}')
print('DvapH  /kJ.mol-1   ', f'{DvapH_CO2:8.3f}  {DvapH_H2O:8.3f}')
print('DvapS  /J.K-1.mol-1', f'{DvapS_CO2:8.3f}  {DvapS_H2O:8.3f}')
#

"""**Chapter 4** Lists and Loops"""

import math
angles = [0, 30, 60, 90, 120, 150, 180]
sines = [round(math.sin(math.radians(x)), 3) for x in angles]
print(sines)
#

"""Example 4.1"""

symbols = ['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne']
print('elements | Z')
print('---------------')
for Z, symbol in enumerate(symbols):
  print('       {:2s} | {:2d}'.format(symbol, Z+1))

symbols = ['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne']
atomic_numbers = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
print('elements | Z')
print('---------------')
for symbol, Z in zip(symbols, atomic_numbers):
  print(f'       {symbol:2s} | {Z:2s}')

# Constituents of dry air: molecule formula, percentage composition by volume
# and molar mass (g.mol--1).
molecule = ['N2', 'O2', 'Ar', 'CO2']
masses = [
    float(input('The mass of N2 is: ')),
    float(input('The mass of O2 is: ')),
    float(input('The mass of Ar is: ')),
    float(input('The mass of CO2 is: '))]
list(zip(molecule, masses))

composition_Of_N2 = float(input('The percentage composition of N2 is: '))
composition_Of_O2 = float(input('The percentage composition of O2 is: '))
composition_Of_Ar = float(input('The percentage composition of Ar is: '))
composition_Of_CO2 = float(input('The percentage composition of CO2 is: '))

print('Molecule' + ' '*10 + 'Mass/Da' + ' '*5 + 'Composition/%')
print('-'*40)
print('molecule[1]:     ',f'{masses[0]:6.3f}   {composition_Of_N2:6.3f}')
print('molecule[2]:     ',f'{masses[1]:6.3f}   {composition_Of_O2:6.3f}')
print('molecule[3]:    ',f'{masses[2]:6.3f}    {composition_Of_Ar:6.3f}')
print('molecule[4]:     ',f'{masses[3]:6.3f}   {composition_Of_CO2:6.3f}')
#

# We have M air = Sigma[i](XiMi)

mean_air_mass = 0
composition = [
    composition_Of_N2,
    composition_Of_O2,
    composition_Of_Ar,
    composition_Of_CO2
]
for m, x_perc in zip(masses, composition):
  mean_air_mass += m*x_perc/100
print(f'The mean air mass is: {mean_air_mass:.2f} g.mol-1')

"""Example 4.3"""

